#!/usr/bin/env python3
"""
Demo script showing the sharing feature workflow.
This simulates the complete sharing flow without requiring a running server.
"""

import secrets
import json
from datetime import datetime

def demo_sharing_workflow():
    """Demonstrate the complete sharing workflow"""
    
    print("🏗️  ArchAI Sharing Feature Demo")
    print("=" * 50)
    
    # 1. Simulate project completion
    print("\n1️⃣  Project Completed")
    project = {
        "id": "proj_123456789",
        "name": "Modern Villa Design",
        "status": "complete",
        "plot_area_sqm": 500,
        "floors": 2,
        "latitude": 18.5204,
        "longitude": 73.8567,
        "share_token": None,
        "is_public": False
    }
    print(f"   📋 Project: {project['name']}")
    print(f"   📍 Location: {project['latitude']}, {project['longitude']}")
    print(f"   🔒 Status: Private")
    
    # 2. User clicks "Share" button
    print("\n2️⃣  User Clicks Share Button")
    print("   🖱️  POST /api/projects/proj_123456789/share")
    
    # 3. Generate secure token
    token = secrets.token_urlsafe(16)
    share_url = f"http://localhost:3000/share/{token}"
    
    project["share_token"] = token
    project["is_public"] = True
    
    print(f"   🔑 Generated token: {token}")
    print(f"   🔗 Share URL: {share_url}")
    print(f"   🌐 Status: Public")
    
    # 4. Simulate sharing the link
    print("\n3️⃣  Link Shared")
    print("   📱 User copies link to clipboard")
    print("   📧 Sends to friend via email/message")
    print("   📱 Or shows QR code for mobile scanning")
    
    # 5. Friend accesses the link
    print("\n4️⃣  Friend Opens Link")
    print(f"   🌐 GET /api/projects/shared/{token}")
    
    # Simulate public project data (no sensitive fields)
    public_data = {
        "id": project["id"],
        "name": project["name"],
        "plot_area_sqm": project["plot_area_sqm"],
        "floors": project["floors"],
        "latitude": project["latitude"],
        "longitude": project["longitude"],
        "design_variants": [
            {
                "id": "var_001",
                "variant_number": 1,
                "score": 87.5,
                "model_url": "https://storage.supabase.co/models/villa_001.glb"
            }
        ],
        "cost_estimate": {
            "total_cost_inr": 2500000,
            "cost_per_sqft": 5000
        },
        "compliance_check": {
            "passed": True,
            "fsi_used": 1.2,
            "fsi_allowed": 1.5
        }
    }
    
    print("   ✅ Public data retrieved successfully")
    print(f"   🏠 Viewing: {public_data['name']}")
    print(f"   💰 Cost: ₹{public_data['cost_estimate']['total_cost_inr']:,}")
    print(f"   📊 Design Score: {public_data['design_variants'][0]['score']}/100")
    
    # 6. Friend sees call-to-action
    print("\n5️⃣  Call to Action")
    print("   🎯 'Want Your Own AI-Generated Building Design?'")
    print("   🔗 'Start for Free on ArchAI ↗'")
    print("   📈 Potential new user acquisition!")
    
    # 7. Optional: Revoke sharing
    print("\n6️⃣  Optional: Revoke Sharing")
    print("   🖱️  DELETE /api/projects/proj_123456789/share")
    
    project["share_token"] = None
    project["is_public"] = False
    
    print("   🔒 Link revoked - now returns 404")
    print("   🔒 Status: Private again")
    
    print("\n" + "=" * 50)
    print("✨ Demo Complete!")
    print("\n📊 Benefits:")
    print("   • Viral sharing of impressive designs")
    print("   • No-friction user acquisition")
    print("   • Showcase ArchAI capabilities")
    print("   • Social proof through real projects")
    print("   • SEO benefits from public pages")
    
    return True

def demo_qr_code():
    """Show QR code generation example"""
    print("\n📱 QR Code Demo")
    print("-" * 30)
    
    share_url = "http://localhost:3000/share/abc123def456"
    print(f"URL: {share_url}")
    print("\nQR Code (ASCII representation):")
    print("█▀▀▀▀▀█ ▀▀█ █▀▀▀▀▀█")
    print("█ ███ █ ▀▀▀ █ ███ █")
    print("█ ▀▀▀ █ █▀█ █ ▀▀▀ █")
    print("▀▀▀▀▀▀▀ ▀ ▀ ▀▀▀▀▀▀▀")
    print("▀▀█▀▀▀▀ ▀█▀ ▀▀█▀▀▀▀")
    print("█▀▀▀▀▀█ ▀▀▀ █▀▀▀▀▀█")
    print("▀▀▀▀▀▀▀ ▀▀▀ ▀▀▀▀▀▀▀")
    print("\n(Real QR code generated by qrcode.react)")

if __name__ == "__main__":
    demo_sharing_workflow()
    demo_qr_code()
    
    print("\n🚀 Ready to implement!")
    print("Run: python3 scripts/test_sharing.py")